# -*- coding: utf-8 -*-
"""Transcribe Youtube Video

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TmJd89amMiEUVKplTawkBq4Wb9q3DCQB

# Installing Dependencies
"""

!pip install pytube3

!pip uninstall pytube

!pip install git+https://github.com/openai/whisper.git -q

"""# Extracting Audio from Youtube video"""

import pytube

video = "https://www.youtube.com/watch?v=q-HNphrWsDE"
data = pytube.YouTube(video)

audio = data.streams.get_audio_only()
audio.download()

import whisper

model = whisper.load_model("base")
text = model.transcribe("/content/Scraping ArXiv Papers with OpenAIs GPT 35 — AI Assistant 2.mp4")

text['text']

new_text = text['text']

text_file = open('/content/read1.txt', 'w')
n = text_file.write(new_text)
text_file.close